// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";



const SUPABASE_URL = "https://ecwhbakitwjeysylirgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjd2hiYWtpdHdqZXlzeWxpcmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDIxNDcsImV4cCI6MjA3MDExODE0N30.nBrPayAqWYY4yiytZKvC6Ppf-CtH8KQV-AsP-1PvzSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});